### ISSUE TITLE
Wrong lib call in test

### ISSUE THREAD

**Issue by cprudhom** [xcsp3team/pycsp3#2]
Have a look at:
https://github.com/xcsp3team/pycsp3/blob/6a66bc6f78d10ec0bc195e8bad3af5f3f547260c/problems/g6_testing/TestAbscon.py#L18

I bet a call to AbsCon would be more convenient.

**Comment by lecoutre** [comment]
You are right.
This was for testing Choco ;-)
I have fixed that.

I have also modified a little bit the guide : https://github.com/xcsp3team/pycsp3/blob/master/guidePyCSP3.pdf
Mostly, the figures ;-)

I will contact you soon about the parameters of solvers.

**Comment by xcsp3team** [comment]
Problem fixed
