### ISSUE TITLE
-data gets concatenated to xml filename

### ISSUE THREAD

**Issue by Rynhho** [xcsp3team/pycsp3#23]
When calling a python file, named **csp.py**, the xml output filename should be **csp.xml**, but if you add data using -data, the xml output filename becomes **csp-data.xml**

**Comment by xcsp3team** [comment]
If you have no data, for example 
  python3 pycsp3/problems/csp/single/SuperNumber.py
you obtain SuperNumber.xml
which is logical

If you have elementary data, as for example : 
  python3 pycsp3/problems/csp/academic/DiamondFree.py -data=8
you obtain DiamondFree-8.xml
which is logical

If now you use a json file as data, as for example :
 python3 pycsp3/problems/csp/real/Areas.py -data=pycsp3/problems/data/json/Areas-3-3-3.json
you obtain Areas-Areas-3-3-3.xml

Here, we can find that Areas-3-3-3.xml would be more appropriate
But imagine that your json file is called 3-3-3.json, we have:
python3 pycsp3/problems/csp/real/Areas.py -data=pycsp3/problems/data/json/3-3-3.json
you obtain Areas-3-3-3.xml
and this times, we find this more logical.

So there is no solution that seems always satisfactory.

One solution could be to check if the name of the JSON has the same prefix than the name of model,
and in that case to discard it. We may change that in the next version.

Also, something new is the option -output.
For example,
  python3 pycsp3/problems/csp/real/Areas.py -data=pycsp3/problems/data/json/Areas-3-3-3.json -output=toto.xml
and we obtain toto.xml

This option is avalaible on github (when cloning) but not in the Pypi version.

Does that answer your question?

**Comment by Rynhho** [comment]
Yes, thank you!
