### ISSUE TITLE
Some typos in the online documentation http://pycsp.org

### ISSUE THREAD

**Issue by hwattez** [xcsp3team/pycsp3#26]
# Some typos in the online documentation http://pycsp.org

## [- PyCSP3 documentation](http://www.pycsp.org)
- [x] Le titre de la page est la forme ‘- PyCSP3 documentation’ : manque-t-il un ‘Homepage’ ?
- [x] PySCP3 -> PyCSP3

## [Installation - PyCSP3 documentation](http://pycsp.org/documentation/installation)
* Pas de souci, l’installation sur Mac se déroule bien.
* Pas nécessaire d’utiliser le sudo de mon côté.

## [QuickStart - PyCSP3 documentation](http://pycsp.org/documentation/QuickStart)
- [ ] Le lien de téléchargement des notebooks montrent le code source et ne produit pas le téléchargement de celui-ci :
	* `<a href="/path/to/your/receipt.pdf" download>Download Receipt</a>`
	* Le mot clé download le permet certainement
* L’exécution fonctionne bien.
- [x] Le message `Warning: Unknown option: -f` apparait au moment de l’import

## [components - PyCSP3 documentation](http://pycsp.org/documentation/components/)
* Pas de souci pour les notebooks variables, contraintes, … tous s’exécutent très bien.

## [Module - PyCSP3 documentation](http://pycsp.org/documentation/interface/ModuleInterface/)
- [x] Certains caractères Latex : `/status()/}: returns the result of the last solving process (last call to \nn{solve()})`

## [Circuit - PyCSP3 documentation](http://pycsp.org/documentation/constraints/Circuit/)
- [x] le Related Models de Mario renvoie vers une page 404
- [x] C’est le cas ici aussi : [Cumulative - PyCSP3 documentation](http://pycsp.org/documentation/constraints/Cumulative/)
- [x] Peut-être d’autres ?

## [Count - PyCSP3 documentation](http://pycsp.org/documentation/constraints/Count/)
- [x] On can infer  -> One can infer 

## [ElementMatrix - PyCSP3 documentation](http://pycsp.org/documentation/constraints/ElementMatrix/)
- [x] at specified indexex -> at specified indexes

## [Extension - PyCSP3 documentation](http://pycsp.org/documentation/constraints/Extension/)
- [x] Sous le titre `Case 3: Starred Tables`, il y a des restes de latex pas interprété

**Comment by xcsp3team** [comment]
Thanks for the typos.

Pages have been updated. T
They will be pushed during November 2022 when the version 2.1 will be published.
