### ISSUE TITLE
TypeError when defining constrains

### ISSUE THREAD

**Issue by YongLei-rst** [xcsp3team/pycsp3#28]
In Vellino sample, there are two variables and a constrains:

c = VarArray(size=nBins, dom=range(nColors))
p = VarArray(size=[nBins, nMaterials], dom=lambda i, j: range(min(maxCapacity, demands[j]) + 1))

satisfy(
    # every bin with a real colour must contain something, and vice versa
    [(c[i] == Unusable) == (Sum(p[i]) == 0) for i in range(nBins)],

    # all components of each material are spread across all bins
    [Sum(p[:, j]) == demands[j] for j in range(nMaterials)],

    # the capacity of each bin is not exceeded
    [Sum(p[i]) <= capacities[c[i]] for i in range(nBins)]
)

![20220424115200](https://user-images.githubusercontent.com/63834540/164955790-8caf0c20-dbdd-40e1-a2fb-71387e2fdaf9.png)

**Comment by xcsp3team** [comment]
It seems that capacities has not the right type. It should be of type ListInt (and not list).
I don't see how you handle capacities.
Loading from a JSON file ?
If this is not the case, you may need to write:
   capacities = cp_array(capacities)

If the problem remains, just send the the complete procedure (required files) and the command you type.

  Best.

**Comment by YongLei-rst** [comment]
In my code, just follow the sample in document, i defined it as capacities = [3, 1, 4].

Now with you suggestion "capacities = cp_array(capacities)", it works

Great appreciation!
