### ISSUE TITLE
Add the possibility to store log of solver and generated xml files in a specific directory.

### ISSUE THREAD

**Issue by audemard** [xcsp3team/pycsp3#30]

**Comment by xcsp3team** [comment]
The use of the option -output has been extended:

You can give the name of the XML files as eg : 
 ```python3 Audrey.py -data=5 -output=toto -dataexport -lzma -solve```
 Then, you get 4 files in the current directory:
```solver_0x42380e86ca_31176_0.log  toto.json  toto.xml  toto.xml.lzma```


You can give the name of a directory :
 ```python3 Audrey.py -data=5 -output=tt -dataexport -lzma -solve```
 Then, you get 4 files in the existing directory called tt :
```Audrey-5.json  Audrey-5.xml  Audrey-5.xml.lzma  solver_0x42380e86ca_32626_0.log```


You can give the name of a file in a specific directory :
```python3 Audrey.py -data=5 -output=tt -dataexport -lzma -solve```
 Then, you get 4 files in the current directory:
```solver_0x42380e86ca_31176_0.log  toto.json  toto.xml  toto.xml.lzma```

In  a notebook, you should be able to write for example:
     from pycsp3.dashboard import options
      options.output="/tmp"
