### ISSUE TITLE
Possible error in the Taillard-js-015-15-1.json data file!

### ISSUE THREAD

**Issue by cs-jlopezr** [xcsp3team/pycsp3#32]
I am checking the specification of the instances in http://jobshop.jjvh.nl/instance.php?instance_id=84 and apparently, there is no correspondence between the data file that you provide and the specification of the corresponding instance. For example, I couldn't find a Job with the following durations: 86,60,10,59,65,94,71,25,98,49,43,8,90,21,73.

**Comment by xcsp3team** [comment]
It seems that the instance with index 1 is the second one of Taillard:  
http://jobshop.jjvh.nl/instance.php?instance_id=85
Do you confirm?
This is because I always start at 0 (but I admit that it is confusing here).

**Comment by cs-jlopezr** [comment]
Yes, you are right! Thank you very much!
