### ISSUE TITLE
Syntax warning: "is" used with literal. Did you mean "==" in compiler.py:271

### ISSUE THREAD

**Issue by wjsuijlenh** [xcsp3team/pycsp3#34]
Python 3.10.6  (default on Ubuntu 22.04) gives a syntax warning about the suspicious use of "is" instead of "==" in the condition on line 271 of compiler.py:
```py
 if Compilation.filename is "" and options.output is not None:
```

When I read the line, I also assume `Compilation.filname == ""` is meant instead.
```py
 if Compilation.filename == "" and options.output is not None:
```

**Comment by xcsp3team** [comment]
Thanks for the issue.
The modification has been performed and pushed
