### ISSUE TITLE
Error when initializing solve() function with 'options' parameter

### ISSUE THREAD

**Issue by hari-2904** [xcsp3team/pycsp3#36]
I am currently working on a Constraint Optimization Problem (COP) using the pyCSP3 library. However, I encountered an error when trying to initialize the solve() function with the options parameter. The error message in the solver log file reads:

**! ERROR: limit=60s is not put at the right position
Use the solver option -ev for more details**

Here's the code snippet where the error occurs:

**if solve(options=["limit=60s"]) in {SAT, OPTIMUM}:
    print(f"Solution: {values(x)}")**

To set a time limit of 60 seconds, I used the options parameter with the value "limit=60s". However, it seems that I am not passing the argument properly to the options parameter.

Could you please provide guidance on how to rectify this error and correctly pass the time limit argument to the options parameter in the solve() function?

Thank you for your assistance!

**Comment by xcsp3team** [comment]
Sorry for the delay (it seems that the message was not sent or received).

A first quick answer is that you can use specific options for the solver.
The value to 'options' is added to the command line used to run the solver.
For example, you can test :

if solve(verbose=0, options="-t=10s") in (SAT, OPTIMUM):
    print(values(x))

The value "-t=10s' is valid for the solver ACE.

I am going to check a few things, and will post an additional part for the answer

**Comment by xcsp3team** [comment]
We have to improve the documentation here (concerning the way to pass options to solvers).
To answer your questions, in addition to the first possible statement of my previous answer, you can also write:

  if solve(solver="ACE,v,limit=4s") is SAT:

or

  if solve(solver="CHOCO,v,limit=4s") is SAT:

Of course, note that v (for verbose) can be discarded.

**Comment by hari-2904** [comment]
Thank you very much for the responce. This  worked. I'm gonna go ahead and close the issue now.
