### ISSUE TITLE
Cannot run PyCSP3 model with exec

### ISSUE THREAD

**Issue by Yuliang795** [xcsp3team/PyCSP3#52]
Hi, 
I have a cp model in PyCSP3 that works fine when executed individually, but when running the code through `exec`, I receive a `TypeError: 'NoneType' object is not subscriptable` error. 

Here’s a minimal example that reproduces the error:
python=3.9.19
pycsp3=2.3.1

```python
c1 = """
from pycsp3 import *
def model_func(data_dict):
    
    n = data_dict['n']

    # s is the series we are trying to find, it's a permutation of 0, 1, ..., n-1
    s = VarArray(size=n, dom=range(n))

    # v represents the intervals between consecutive elements in s
    v = VarArray(size=n-1, dom=range(1, n))

    # Constraint 1: s is a permutation of the set {0, 1, ..., n-1}
    satisfy(
        AllDifferent(s)
    )

    # Constraint 2: v is the absolute difference between consecutive elements in s
    satisfy(
        v[i] == abs(s[i+1] - s[i]) for i in range(n-1)
    )

    # Constraint 3: v is a permutation of the set {1, 2, ..., n-1}
    satisfy(
        AllDifferent(v)
    )

    return {'s': s, 'v': v}

data_dict={"n":12}
model_func(data_dict)

"""
exec(c1)
```

Expected output:
```
python:{'s': [s[0],
  s[1],
  s[2],
  s[3],
  s[4],
  s[5],
  s[6],
  s[7],
  s[8],
  s[9],
  s[10],
  s[11]],
 'v': [v[0], v[1], v[2], v[3], v[4], v[5], v[6], v[7], v[8], v[9], v[10]]}
```

Can you please check if this is an compatibility issue with exec?

Thanks

**Comment by xcsp3team** [comment]
Because of the way we use `inspect` it seems that we got a similar problem as the one described here:
  [stackoverflow](https://stackoverflow.com/questions/63347543/python-inspect-stack-returns-frameinfo-objects-with-missing-code-context-a)

"The only way that the inspect module can display source code is if the code came from a file that it can access. Source typed at an interactive prompt is discarded as soon as it is parsed, there's simply no way for inspect to access it. – @jasonharper"

However, I am not 100% sure.
I will ask Nicolas.

  Best.

**Comment by szczepanskiNicolas** [comment]
Hello @Yuliang795, 

In PyCSP3, we use the “inspect” library (https://docs.python.org/3/library/inspect.html) to provide certain additional functions, such as retrieving the variable names of the Var() and VarArray() functions. 

For example, in `s = VarArray(size=n, dom=range(n))`, the name "s" was found thanks to the inspector. 

Unfortunately, the latter needs a file with the code written in it.  What is more, certain language enhancements with the forbiddenfruit library require this file with the code. 

It seems that the exec function does not load the python context required by these two librairies.

A solution is to use two files and the "subprocess" module: 

```
import subprocess
subprocess.run(['python', 'c1.py'])

```
This way, you can put or modify anything you like in "c1.py". 

Best regards

**Comment by Yuliang795** [comment]
> Hello @Yuliang795,
> 
> In PyCSP3, we use the “inspect” library (https://docs.python.org/3/library/inspect.html) to provide certain additional functions, such as retrieving the variable names of the Var() and VarArray() functions.
> 
> For example, in `s = VarArray(size=n, dom=range(n))`, the name "s" was found thanks to the inspector.
> 
> Unfortunately, the latter needs a file with the code written in it. What is more, certain language enhancements with the forbiddenfruit library require this file with the code.
> 
> It seems that the exec function does not load the python context required by these two librairies.
> 
> A solution is to use two files and the "subprocess" module:
> 
> ```
> import subprocess
> subprocess.run(['python', 'c1.py'])
> ```
> 
> This way, you can put or modify anything you like in "c1.py".
> 
> Best regards

Thank you for confirming this and the detailed explanation.
