### ISSUE TITLE
Feature Request: Possible Acceleration?

### ISSUE THREAD

**Issue by SMUEric1127** [xcsp3team/pycsp3#53]
Hi team,

Thank you so much for creating this library, do guys know what are some possible way to speed up the solver() and satisfy()? I followed the tutorial with Social Golfer Problems with a relatively small instance (same as tutorial) and it still took longer time. In cases where there would be larger instance, what are possible ways I can speed up this process?

Thank you!

**Comment by xcsp3team** [comment]
The problems we have to solve are typically NP-complete, meaning that there does not exist any known polynomial algorithms to solve them. Since a few decades, researchers are trying to develop the most possible effective techniques.
